'use strict';
// Editor explícito por dia: as mesmas premissas da matriz, sem outra cópia de cálculo.
let editDay=0;
const editableNumber=v=>v===null?'':String(Math.round(v));
function parseVolume(text){const s=text.trim();if(!s)return null;if(!/^(?:\d+(?:[.,]\d*)?|\d{1,3}(?:\.\d{3})+,\d+)$/.test(s))return NaN;return Number(s.includes(',')?s.replace(/\./g,'').replace(',','.'):s);}
function renderEditor(){
 const box=$('daily-editor');if(!box)return;
 // select() (app.js) pode ficar sem record quando o filtro de regiao zera a lista de bases; sem essa
 // guarda, editorSummary() abaixo quebra em record.bi (record seria undefined).
 if(!record){box.innerHTML='';$('edit-days').innerHTML='';return;}
 $('edit-days').innerHTML=Array.from({length:n},(_,i)=>`<button type="button" data-edit-day="${i}" class="${i===editDay?'active':''}" aria-pressed="${i===editDay}">${label(i)}<small>${i===0?'Abertura':new Date(day(i)+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short'})}</small></button>`).join('');
 const field=(k,l,v)=>`<label title="${esc(k==='opening'?'Abertura da planilha diária, litros ÷ 1.000':sourceNote(k,editDay))}">${esc(l)}<div class="volume-field"><input type="text" inputmode="decimal" data-edit-key="${k}" value="${editableNumber(v)}" aria-label="${esc(l)} em ${label(editDay)}" autocomplete="off"><span>m³</span></div><small>${k==='opening'?'Abertura importada':['sale','fob','cif','pump','transferIn','transferOut'].includes(k)?'Importado das fontes · editável':'Ajuste opcional'}</small></label>`;
 box.innerHTML=`<div class="edit-group"><h3>Estoque inicial</h3>${editDay===0?field('opening','Abertura do dia',state.opening):`<p>Abertura calculada: <strong id="day-opening">${fmt(E.calculate(state,n)[editDay].opening)} m³</strong></p><small>Vem do fechamento anterior. Altere os movimentos para testar outro saldo.</small>`}</div>`+
 [1,-1].map(sign=>`<div class="edit-group ${sign>0?'in':'out'}"><h3>${sign>0?'＋ Entradas':'− Saídas'}</h3><div class="edit-fields">${E.rows.filter(r=>r[2]===sign&&!['transferIn','transferOut'].includes(r[0])).map(([k,l])=>field(k,l,state.movements[k][editDay])).join('')}</div></div>`).join('');
 editorSummary();
}
function editorSummary(){if(!$('day-summary'))return;if(!record){$('day-summary').textContent='';if($('stock-gauge'))$('stock-gauge').innerHTML='';if($('bi-measures'))$('bi-measures').innerHTML='';return;}const r=E.calculate(state,n)[editDay];$('day-summary').textContent=`${label(editDay)}: abertura ${fmt(r.opening)} + entradas ${fmt(r.incoming)} − saídas ${fmt(r.outgoing)} = fechamento ${fmt(r.close)} m³`;
 if($('bi-measures')){const values=record.bi.days[day(editDay)]?.scenarios?.[state.scenario]||{},labels=[['lastro','Lastro mínimo'],['pump','Bombeio (programação)'],['progRoad','Rodoviário (programação)'],['plannedSales','Vendas planejadas (LE)'],['actualSales','Vendas hoje (pedidos SAP)'],['availability','Disp. MIS']];$('bi-measures').innerHTML=`<thead><tr><th>Medida · ${esc(state.scenario)} · ${label(editDay)}</th><th>m³</th></tr></thead><tbody>${labels.map(([k,l])=>`<tr><th>${l}</th><td>${fmt(values[k])}</td></tr>`).join('')}</tbody>`;}
 if($('day-opening'))$('day-opening').textContent=fmt(r.opening)+' m³';
 const level=status(r.close),text=r.close<0?'Estoque negativo':level==='danger'?'Estoque no mínimo ou abaixo':level==='warn'?'Entre o mínimo e o médio':level==='good'?'Entre o médio e o máximo':level==='high'?'Acima do estoque máximo':'Sem limites completos na fonte';
 const capacity=state.capacity,percent=capacity>0?Math.max(0,Math.min(100,r.close/capacity*100)):0;
 $('stock-gauge').innerHTML=`<div class="gauge-title ${level}"><strong>● ${text}</strong><span>${fmt(r.close)} m³ ${capacity===null?'':`/ capacidade ${fmt(capacity)} m³`}</span></div><div class="tank"><div class="tank-fill ${level}" style="width:${percent}%"></div>${capacity>0&&state.min!==null?`<span class="min-marker" style="left:${Math.min(100,state.min/capacity*100)}%" title="Mínimo ${fmt(state.min)} m³"></span>`:''}</div><div class="legend"><span style="--c:#8B0000">≤ mínimo</span><span style="--c:#FFA500">≤ médio</span><span style="--c:#90EE90">≤ máximo</span><span style="--c:#008000">Acima do máximo</span></div>${capacity!==null&&r.close>capacity?`<p class="capacity-warning">▲ Capacidade física excedida em ${fmt(r.close-capacity)} m³.</p>`:''}`;
 const calculated=E.calculate(state,n);
 document.querySelectorAll('[data-edit-day]').forEach(button=>{const daily=calculated[+button.dataset.editDay],risk=status(daily.close);button.classList.remove('risk-danger','risk-warn','risk-good','risk-high','risk-neutral');button.classList.add('risk-'+risk);button.title=`${label(+button.dataset.editDay)} · abertura ${fmt(daily.opening)} · fechamento ${fmt(daily.close)} m³`;});
}
function renderHistory(){if(!record){$('history-grid').innerHTML='';return;}const offsets=Array.from({length:7},(_,i)=>i-7);$('history-grid').innerHTML='<thead><tr><th>Histórico · m³</th>'+offsets.map(i=>`<th>${label(i)}</th>`).join('')+'</tr></thead><tbody>'+[['opening','Abertura real'],['received','Recebimento disponível informado'],['planned','Recebimento programado informado'],['sale','Faturamento realizado']].map(([k,l])=>`<tr><th>${l}</th>${offsets.map(i=>`<td>${fmt(history(i)?.[k])}</td>`).join('')}</tr>`).join('')+'</tbody>';}
// deposito/empresa sao multi-selecao de verdade (pedido da usuaria, 2026-10-05) — "ativo" vem dos
// Sets (depositosAtivos/empresasAtivas), nao de o.selected (que so' reflete o <select> de 1 valor so').
function renderChips(){for(const [id,selectId] of [['cidade-chips','cidade'],['deposito-chips','deposito'],['empresa-chips','empresa'],['product-chips','product']]){const ativos=selectId==='deposito'?depositosAtivos:selectId==='empresa'?empresasAtivas:null;$(id).innerHTML=Array.from($(selectId).options).filter(o=>o.value).map(o=>{const ligado=ativos?ativos.has(o.value):o.selected;return `<button type="button" data-select="${selectId}" data-value="${esc(o.value)}" class="${ligado?'active':''}" aria-pressed="${ligado}">${esc(o.text)}</button>`;}).join('');}}
const priorRender=render;
render=function(rebuild=false){priorRender(rebuild);renderHistory();renderChips();if(!record){$('policy-source').textContent='';$('policy-provenance').textContent='';if($('bi-loaded'))$('bi-loaded').innerHTML='';return;}const policy=record.policy;$('policy-source').textContent=policy?`${policy.name} · ${record.product} — limites carregados de Politica Vigente. Alterações valem somente para a simulação.`:'Sem correspondência na planilha de política.';$('policy-provenance').textContent=policy?`Política: ${policy.source} | Aba ${policy.sheet} | Linha ${policy.row}.`:'Política não localizada.';if($('bi-loaded')){const missing=Object.values(record.bi.days).some(d=>d.missingModelRow);$('bi-loaded').innerHTML=`<strong>✓ Valores carregados das fontes · m³</strong> — LE vigente, FOB/CIF, bombeio e programação rodoviária.<small>Extraído em ${esc(D.bi.extractedAt.replace('T',' '))} · ${esc(record.bi.name)} · material ${record.bi.material}. ${missing?'Este recorte não tem linha de dados nas fontes; consulte as lacunas nas dicas dos campos.':'Passe o mouse nos campos para conferir a medida de origem.'}</small>`;}if(rebuild)renderEditor();else editorSummary();};
const selectWithEditor=select;
select=function(){selectWithEditor();renderEditor();};
document.addEventListener('click',e=>{const chip=e.target.closest('[data-select]');if(chip){
 // deposito/empresa: clique LIGA/DESLIGA aquele valor no Set, sem apagar os outros ja ativos — e'
 // como da' pra selecionar varios ao mesmo tempo (pedido da usuaria, 2026-10-05).
 if(chip.dataset.select==='deposito'){if(depositosAtivos.has(chip.dataset.value))depositosAtivos.delete(chip.dataset.value);else depositosAtivos.add(chip.dataset.value);sincronizarSelectMultiplo($('deposito'),depositosAtivos);refreshEmpresaOptions();products();}
 else if(chip.dataset.select==='empresa'){if(empresasAtivas.has(chip.dataset.value))empresasAtivas.delete(chip.dataset.value);else empresasAtivas.add(chip.dataset.value);sincronizarSelectMultiplo($('empresa'),empresasAtivas);products();}
 else {$(chip.dataset.select).value=chip.dataset.value;if(chip.dataset.select==='cidade'){depositosAtivos=new Set();empresasAtivas=new Set();refreshDepositoOptions();products();}else select();}
}
 const dayButton=e.target.closest('[data-edit-day]');if(dayButton){editDay=+dayButton.dataset.editDay;renderEditor();}
});
$('daily-editor').addEventListener('input',e=>{const input=e.target,k=input.dataset.editKey;if(!k)return;const v=parseVolume(input.value);if(v===null||!Number.isFinite(v)||v<0){input.setCustomValidity('Informe um volume válido, maior ou igual a zero.');input.setAttribute('aria-invalid','true');return;}input.setCustomValidity('');input.removeAttribute('aria-invalid');if(k==='opening'){state.opening=v;const p=document.querySelector('[data-param="opening"]');if(p)p.value=Math.round(v);}else {try{E.setMovement(state,k,editDay,v);}catch(err){message(err.message);input.value=editableNumber(state.movements[k][editDay]);return;}}persist();render();const gridInput=document.querySelector(`[data-row="${k}"][data-day="${editDay}"]`);if(gridInput)gridInput.value=Math.round(v);if(['pump','progRoad'].includes(k)){const linked=document.querySelector('[data-edit-key="fob"]');if(linked)linked.value=editableNumber(state.movements.fob[editDay]);const cell=document.querySelector(`[data-row="fob"][data-day="${editDay}"]`);if(cell)cell.value=Math.round(state.movements.fob[editDay]);}});
$('daily-editor').addEventListener('focusout',e=>{const input=e.target,k=input.dataset.editKey;if(!k)return;if(!input.validity.valid||input.value.trim()===''){message('Valor não aplicado. Use um volume positivo ou zero; exemplo: 125,5.');input.value=editableNumber(k==='opening'?state.opening:state.movements[k][editDay]);input.setCustomValidity('');input.removeAttribute('aria-invalid');}input.value=editableNumber(k==='opening'?state.opening:state.movements[k][editDay]);});
$('repeat-day').onclick=()=>{const candidate=structuredClone(state);for(const [k]of E.rows)for(let i=editDay+1;i<n;i++)candidate.movements[k][i]=state.movements[k][editDay];state=candidate;persist();render(true);message('Movimentos repetidos nos dias seguintes da simulação.');};
$('grid').addEventListener('input',()=>{renderEditor();});
$('premises').addEventListener('change',()=>renderEditor());
// Pedido da usuaria, 2026-10-01: tela abre sem nada selecionado (antes vinha com uma base padrao fixa),
// entao pode nao ter "record" ainda neste ponto — sem a guarda, render(true) quebrava em E.calculate
// (state undefined) assim que editor.js carregava, antes de qualquer selecao do usuario.
if(record)render(true);
