'use strict';
(function(root){
const rows=[['received','Recebimento adicional manual',1],['planned','Programação adicional manual',1],['fob','Trânsito FOB · recebimento',1],['cif','Trânsito CIF · recebimento',1],['pump','Bombeio',1],['loanIn','Empréstimo · entrada',1],['transferIn','Transferência · entrada',1],['sale','Vendas · LE vigente',-1],['loanOut','Empréstimo · saída',-1],['transferOut','Transferência · saída',-1]];
// Emprestimos antigos permanecem nos arquivos salvos, mas nao integram a simulacao.
for(let i=rows.length-1;i>=0;i--)if(['loanIn','loanOut'].includes(rows[i][0]))rows.splice(i,1);
function calculate(s,n){let opening=s.opening;return Array.from({length:n},(_,i)=>{let incoming=0,outgoing=0;for(const [key,,sign] of rows){const v=s.movements[key][i];if(sign>0){if(!(['pump','progRoad'].includes(key)&&s.scenario==='Inbound + MIS'&&i>=s.switchIndex))incoming+=v;}else outgoing+=v;}const close=opening+incoming-outgoing;const result={opening,openingNet:s.lastro===null?null:opening-s.lastro,lastro:s.lastro,incoming,outgoing,close,available:s.lastro===null?null:close-s.lastro};opening=close;return result;});}
function validate(s){if(s?.movements && !Object.hasOwn(s.movements,'progRoad'))s.movements.progRoad=Array(30).fill(0);if(!s||s.version!==1||typeof s.id!=='string'||typeof s.date!=='string'||typeof s.name!=='string'||s.name.length>80||typeof s.clamp!=='boolean')throw Error('Estrutura de cenário inválida.');for(const key of ['opening','lastro','min','mid','max','capacity'])if(!(key!=='opening'&&s[key]===null)&&!(typeof s[key]==='number'&&Number.isFinite(s[key])&&s[key]>=0))throw Error('Premissas devem ser números positivos ou zero.');for(const [key]of rows)if(!Array.isArray(s.movements?.[key])||s.movements[key].length!==30||s.movements[key].some(v=>typeof v!=='number'||!Number.isFinite(v)||v<0))throw Error('Movimentações inválidas: informe 30 valores não negativos por linha.');let previous=-Infinity;for(const key of ['min','mid','max'])if(s[key]!==null){if(s[key]<previous)throw Error('Mínimo, médio e máximo devem estar em ordem crescente.');previous=s[key];}if(s.capacity!==null&&s.lastro!==null&&s.lastro>s.capacity)throw Error('Lastro não pode superar a capacidade.');s.clamp=false;return s;}
function stockBand(value,s){if(s.min===null)return 'neutral';if(value<=s.min)return 'danger';if(s.mid!==null&&value<=s.mid)return 'warn';if(s.max!==null&&value<=s.max)return 'good';if(s.max!==null)return 'high';return 'neutral';}
function setMovement(s,k,i,v){if(s.scenario==='Inbound + MIS'&&i>=s.switchIndex){if(['pump','progRoad'].includes(k))s.movements.fob[i]+=v-s.movements[k][i];if(k==='fob'&&v<s.movements.pump[i])throw Error('FOB inclui o bombeio DAP; reduza primeiro o bombeio ou mantenha FOB maior ou igual a ele.');}s.movements[k][i]=v;}
root.StockEngine={rows,calculate,validate,stockBand,setMovement};
})(typeof window!=='undefined'?window:globalThis);
